select * from tab;
SELECT * FROM EMPLOYEES;
ALTER TABLE EMPLOYEES RENAME COLUMN LAST_NAME TO MANAGER;
ALTER TABLE EMPLOYEES ADD NOTES VARCHAR2(20);

Select * from user_sequences;
CREATE SEQUENCE EMP_SEQ
    START WITH 1000;

INSERT INTO EMPLOYEES(EMPLOYEE_ID, MANAGER, NAME, BIRTH_DATE, PHOTO, NOTES)
VALUES(EMP_SEQ.NEXTVAL, 'MANAGER','±è°æ¹Î','900101','KIM.JPG','¸Å´ÏÀú');
SELECT * FROM EMPLOYEES;

