SELECT P.BIRTH_DATE 생년월일,
       P.PLAYER_NAME 선수
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL
ORDER BY P.BIRTH_DATE DESC 
;

SELECT COUNT(*) 선수인원 --468명 
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL
ORDER BY P.BIRTH_DATE DESC 
;

SELECT (SELECT P.BIRTH_DATE
        FROM PLAYER P
        WHERE P.BIRTH_DATE IS NOT NULL 
         ) 생년월일,
       P.PLAYER_NAME 선수
FROM PLAYER P
WHERE ROWNUM BETWEEN 1 AND 10
ORDER BY P.BIRTH_DATE DESC;
   -- AND ROWNUM BETWEEN 1 AND 10


-- 답
SELECT P.BIRTH_DATE 생년월일,
       P.PLAYER_NAME 선수
FROM (SELECT P.PLAYER_NAME, P.BIRTH_DATE
       FROM PLAYER P
       WHERE P.BIRTH_DATE IS NOT NULL  
       ORDER BY P.BIRTH_DATE DESC 
        ) P
WHERE ROWNUM BETWEEN 1 AND 5;

--6페이지 
SELECT P2.SEQ "NO.",
       P2.BIRTH_DATE 생년월일,
       P2.PLAYER_NAME 선수
FROM 
      (SELECT ROWNUM SEQ,P.* FROM 
      (SELECT  P.PLAYER_NAME, P.BIRTH_DATE  
       FROM PLAYER P
       WHERE P.BIRTH_DATE IS NOT NULL  
       ORDER BY P.BIRTH_DATE DESC 
        ) P ) P2

WHERE P2.SEQ BETWEEN 6 AND 10
ORDER BY P2.SEQ ASC 
;


